apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vertigo-ai-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/poetic-orb-474016-q7/vertigo-ai-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
<<<<<<< HEAD
          value: "MONGODB_URI_PLACEHOLDER"
        - name: OPENAI_API_KEY
          value: "OPENAI_API_KEY_PLACEHOLDER"
        - name: JWT_SECRET
          value: "JWT_SECRET_PLACEHOLDER"
=======
          value: "mongodb+srv://denisbartolomei:Mongoloide1996PazzoScAt3nAt0@clustervertigousertest.apfzk47.mongodb.net/?retryWrites=true&w=majority&appName=ClusterVertigoUserTest"
        - name: OPENAI_API_KEY
          value: "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"
        - name: JWT_SECRET
          value: "5e8b03820f8868497daebb2e108bfe2f"
>>>>>>> 529759e (Nuove modifiche per upload in cloud)
        - name: PYTHON_ENV
          value: "production"
        resources:
          limits:
            cpu: "2"
            memory: "4Gi"
          requests:
            cpu: "1"
            memory: "2Gi"