apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: vertigo-ai-backend
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "true"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/poetic-orb-474016-q7/vertigo-ai-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: MONGODB_URI
          value: "MONGODB_URI_PLACEHOLDER"
        - name: AZURE_OPENAI_ENDPOINT
          value: "AZURE_OPENAI_ENDPOINT_PLACEHOLDER"
        - name: AZURE_OPENAI_API_KEY
          value: "AZURE_OPENAI_API_KEY_PLACEHOLDER"
        - name: AZURE_OPENAI_API_VERSION
          value: "AZURE_OPENAI_API_VERSION_PLACEHOLDER"
        - name: AZURE_OPENAI_DEPLOYMENT_NAME
          value: "AZURE_OPENAI_DEPLOYMENT_NAME_PLACEHOLDER"
        - name: JWT_SECRET
          value: "JWT_SECRET_PLACEHOLDER"
        - name: PYTHON_ENV
          value: "production"
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
          requests:
            cpu: "0.5"
            memory: "1Gi"
